export const CANVAS_WIDTH = window.innerWidth;
export const CANVAS_HEIGHT = 569;
export const BACKGROUND_WIDTH = 3381;
export const MID_FIELD_Y = 430;
export const MID_FIELD_X = BACKGROUND_WIDTH / 2;
export const BALL_GRAVITY = 0.2;
export const PLAYER_GRAVITY = 0.3;
export const BOUNCE_DAMPING = 0.9;
export const PLAYER_WIDTH = 67;
export const PLAYER_HEIGHT = 77;
export const PLAYER_JUMP_VELOCITY = -15;
export const PLAYER_MOVE_SPEED = 5;
export const BALL_WIDTH = 60;
export const BALL_HEIGHT = 60;
export const BALL_START_HEIGHT = 500; // Height above the player
export const LEFT_BOUNDARY = 240;
export const RIGHT_BOUNDARY = 3140;
// export const BALL_STARTING_POS_X = CANVAS_WIDTH - BALL_WIDTH / 2;
export const BALL_STARTING_POS_Y = 110;
